<?php

namespace App\Services;

use App\Support\FinancialActor;
use App\Support\Money;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

/** Mutation boundary for observations and allocations; it never writes journals. */
final class FinancialReconciliationService
{
    public function __construct(private readonly OperationalAuditService $audit) {}

    public function create(Request $request, int $tenantId, array $data, int $actorId): object
    {
        return DB::transaction(function () use ($request, $tenantId, $data, $actorId): object {
            if (! empty($data['idempotencyKey']) && ($existing = DB::table('financial_reconciliations')->where('tenant_id', $tenantId)->where('idempotency_key', $data['idempotencyKey'])->lockForUpdate()->first())) { FinancialActor::assertBranchAccess($actorId, $tenantId, $existing->branch_id ? (int) $existing->branch_id : null); if ($existing->idempotency_fingerprint !== $this->fingerprint($data)) throw ValidationException::withMessages(['idempotencyKey' => 'This idempotency key was already used with different reconciliation data.']); return $existing; }
            $target = $this->target($tenantId, $data, $actorId); [$opening, $closing] = $this->balances($tenantId, $target->financial_account_id, $data['dateFrom'], $data['dateTo']);
            $id = (int) DB::table('financial_reconciliations')->insertGetId(['tenant_id' => $tenantId, 'branch_id' => $target->branch_id, 'financial_account_id' => $target->financial_account_id, 'financial_location_id' => $target->financial_location_id, 'payment_method_id' => $target->payment_method_id, 'reference' => $this->nextReference($tenantId), 'idempotency_key' => $data['idempotencyKey'] ?? null, 'idempotency_fingerprint' => ! empty($data['idempotencyKey']) ? $this->fingerprint($data) : null, 'type' => $data['type'], 'status' => 'draft', 'date_from' => $data['dateFrom'], 'date_to' => $data['dateTo'], 'book_opening_balance' => Money::decimal($opening), 'book_closing_balance' => Money::decimal($closing), 'external_opening_balance' => $this->moneyOrNull($data['externalOpeningBalance'] ?? null), 'external_closing_balance' => $this->moneyOrNull($data['externalClosingBalance'] ?? null), 'actual_cash_count' => $this->moneyOrNull($data['actualCashCount'] ?? null), 'difference' => $this->difference($data['type'], $closing, $data), 'notes' => $data['notes'] ?? null, 'created_by' => $actorId, 'created_at' => now(), 'updated_at' => now()]);
            $row = $this->find($tenantId, $id, true); $this->audit->record($request, $tenantId, 'financial_reconciliation.created', 'financial_reconciliation', $id, [], (array) $row, $row->branch_id, $actorId); return $row;
        });
    }

    public function update(Request $request, int $tenantId, int $id, array $data, int $actorId): object
    {
        return DB::transaction(function () use ($request, $tenantId, $id, $data, $actorId): object { $row = $this->find($tenantId, $id, true); $this->editable($row, $tenantId, $actorId); $payload = ['external_opening_balance' => array_key_exists('externalOpeningBalance', $data) ? $this->moneyOrNull($data['externalOpeningBalance']) : $row->external_opening_balance, 'external_closing_balance' => array_key_exists('externalClosingBalance', $data) ? $this->moneyOrNull($data['externalClosingBalance']) : $row->external_closing_balance, 'actual_cash_count' => array_key_exists('actualCashCount', $data) ? $this->moneyOrNull($data['actualCashCount']) : $row->actual_cash_count, 'notes' => $data['notes'] ?? $row->notes, 'status' => 'in_progress', 'updated_at' => now()]; $payload['difference'] = $this->storedDifference($row, $payload); DB::table('financial_reconciliations')->where('tenant_id', $tenantId)->where('id', $id)->update($payload); $after = $this->find($tenantId, $id, true); $this->audit->record($request, $tenantId, 'financial_reconciliation.updated', 'financial_reconciliation', $id, (array) $row, (array) $after, $after->branch_id, $actorId); return $after; });
    }

    public function addLine(Request $request, int $tenantId, int $sessionId, array $data, int $actorId): object
    {
        return DB::transaction(function () use ($request, $tenantId, $sessionId, $data, $actorId): object { $session = $this->find($tenantId, $sessionId, true); $this->editable($session, $tenantId, $actorId); if (! empty($data['externalIdentifier']) && ($existing = DB::table('financial_reconciliation_statement_lines')->where('tenant_id', $tenantId)->where('financial_reconciliation_id', $sessionId)->where('external_identifier', $data['externalIdentifier'])->lockForUpdate()->first())) return $existing; $id = (int) DB::table('financial_reconciliation_statement_lines')->insertGetId(['tenant_id' => $tenantId, 'financial_reconciliation_id' => $sessionId, 'transaction_date' => $data['transactionDate'], 'value_date' => $data['valueDate'] ?? null, 'reference' => $data['reference'] ?? null, 'description' => $data['description'], 'amount' => Money::decimal(Money::cents($data['amount'])), 'direction' => $data['direction'], 'external_identifier' => $data['externalIdentifier'] ?? null, 'created_by' => $actorId, 'created_at' => now(), 'updated_at' => now()]); DB::table('financial_reconciliations')->where('id', $sessionId)->update(['status' => 'in_progress', 'updated_at' => now()]); $line = $this->line($tenantId, $sessionId, $id, true); $this->audit->record($request, $tenantId, 'financial_reconciliation.statement_line_added', 'financial_reconciliation', $sessionId, [], ['statementLineId' => $id], $session->branch_id, $actorId); return $line; });
    }

    public function updateLine(Request $request, int $tenantId, int $sessionId, int $lineId, array $data, int $actorId): object { return DB::transaction(function () use ($request, $tenantId, $sessionId, $lineId, $data, $actorId): object { $session = $this->find($tenantId, $sessionId, true); $this->editable($session, $tenantId, $actorId); $line = $this->line($tenantId, $sessionId, $lineId, true); if (DB::table('financial_reconciliation_matches')->where('tenant_id', $tenantId)->where('statement_line_id', $lineId)->exists()) throw ValidationException::withMessages(['statementLine' => 'Matched statement lines cannot be edited.']); DB::table('financial_reconciliation_statement_lines')->where('id', $lineId)->update(['transaction_date' => $data['transactionDate'] ?? $line->transaction_date, 'value_date' => array_key_exists('valueDate', $data) ? $data['valueDate'] : $line->value_date, 'reference' => array_key_exists('reference', $data) ? $data['reference'] : $line->reference, 'description' => $data['description'] ?? $line->description, 'amount' => array_key_exists('amount', $data) ? Money::decimal(Money::cents($data['amount'])) : $line->amount, 'direction' => $data['direction'] ?? $line->direction, 'updated_at' => now()]); $after = $this->line($tenantId, $sessionId, $lineId, true); $this->audit->record($request, $tenantId, 'financial_reconciliation.statement_line_updated', 'financial_reconciliation', $sessionId, (array) $line, (array) $after, $session->branch_id, $actorId); return $after; }); }
    public function deleteLine(Request $request, int $tenantId, int $sessionId, int $lineId, int $actorId): void { DB::transaction(function () use ($request, $tenantId, $sessionId, $lineId, $actorId): void { $session = $this->find($tenantId, $sessionId, true); $this->editable($session, $tenantId, $actorId); $this->line($tenantId, $sessionId, $lineId, true); if (DB::table('financial_reconciliation_matches')->where('tenant_id', $tenantId)->where('statement_line_id', $lineId)->exists()) throw ValidationException::withMessages(['statementLine' => 'Matched statement lines cannot be deleted.']); DB::table('financial_reconciliation_statement_lines')->where('tenant_id', $tenantId)->where('id', $lineId)->delete(); $this->audit->record($request, $tenantId, 'financial_reconciliation.statement_line_deleted', 'financial_reconciliation', $sessionId, [], ['statementLineId' => $lineId], $session->branch_id, $actorId); }); }

    public function match(Request $request, int $tenantId, int $sessionId, array $data, int $actorId): object { return DB::transaction(function () use ($request, $tenantId, $sessionId, $data, $actorId): object { $session = $this->find($tenantId, $sessionId, true); $this->editable($session, $tenantId, $actorId); if (! empty($data['idempotencyKey']) && ($existing = DB::table('financial_reconciliation_matches')->where('tenant_id', $tenantId)->where('financial_reconciliation_id', $sessionId)->where('idempotency_key', $data['idempotencyKey'])->first())) return $existing; $line = $this->line($tenantId, $sessionId, (int) $data['statementLineId'], true); $journal = DB::table('journal_entries')->where('tenant_id', $tenantId)->where('id', $data['journalEntryId'])->where('status', 'posted')->lockForUpdate()->first(); if (! $journal || ! $this->journalAmount($tenantId, $session, $journal)) throw ValidationException::withMessages(['journalEntryId' => 'Select a posted transaction for this reconciliation account and period.']); if ($line->direction !== $this->journalDirection($tenantId, $session, $journal)) throw ValidationException::withMessages(['journalEntryId' => 'Statement and system transaction directions must match.']); $amount = Money::cents($data['amount']); if ($amount <= 0 || $amount > $this->remainingLine($tenantId, $line) || $amount > $this->remainingJournal($tenantId, $session, $journal)) throw ValidationException::withMessages(['amount' => 'Match amount exceeds the remaining statement line or system transaction amount.']); $id = (int) DB::table('financial_reconciliation_matches')->insertGetId(['tenant_id' => $tenantId, 'financial_reconciliation_id' => $sessionId, 'statement_line_id' => $line->id, 'journal_entry_id' => $journal->id, 'matched_amount' => Money::decimal($amount), 'idempotency_key' => $data['idempotencyKey'] ?? null, 'created_by' => $actorId, 'created_at' => now(), 'updated_at' => now()]); $match = DB::table('financial_reconciliation_matches')->where('id', $id)->first(); $this->audit->record($request, $tenantId, 'financial_reconciliation.match_created', 'financial_reconciliation', $sessionId, [], ['matchId' => $id], $session->branch_id, $actorId); return $match; }); }
    public function unmatch(Request $request, int $tenantId, int $sessionId, int $matchId, int $actorId): void { DB::transaction(function () use ($request, $tenantId, $sessionId, $matchId, $actorId): void { $session = $this->find($tenantId, $sessionId, true); $this->editable($session, $tenantId, $actorId); $match = DB::table('financial_reconciliation_matches')->where('tenant_id', $tenantId)->where('financial_reconciliation_id', $sessionId)->where('id', $matchId)->lockForUpdate()->first(); abort_unless($match, 404); DB::table('financial_reconciliation_matches')->where('id', $matchId)->delete(); $this->audit->record($request, $tenantId, 'financial_reconciliation.match_removed', 'financial_reconciliation', $sessionId, ['matchId' => $matchId], [], $session->branch_id, $actorId); }); }
    public function complete(Request $request, int $tenantId, int $id, int $actorId, FinancialReconciliationQueryService $query): object { return DB::transaction(function () use ($request, $tenantId, $id, $actorId, $query): object { $session = $this->find($tenantId, $id, true); FinancialActor::assertBranchAccess($actorId, $tenantId, $session->branch_id ? (int) $session->branch_id : null); if ($session->status === 'completed') return $session; $this->editable($session, $tenantId, $actorId); $blockers = $query->blockers($tenantId, $session); if ($blockers !== []) throw ValidationException::withMessages(['reconciliation' => $blockers]); if (DB::table('financial_reconciliations')->where('tenant_id', $tenantId)->where('financial_account_id', $session->financial_account_id)->where('status', 'completed')->whereDate('date_from', '<=', $session->date_to)->whereDate('date_to', '>=', $session->date_from)->exists()) throw ValidationException::withMessages(['reconciliation' => ['OVERLAPPING_RECONCILIATION']]); DB::table('financial_reconciliations')->where('id', $id)->update(['status' => 'completed', 'completed_by' => $actorId, 'completed_at' => now(), 'updated_at' => now()]); $after = $this->find($tenantId, $id, true); $this->audit->record($request, $tenantId, 'financial_reconciliation.completed', 'financial_reconciliation', $id, (array) $session, (array) $after, $after->branch_id, $actorId); return $after; }); }
    public function find(int $tenantId, int $id, bool $lock = false): object { $q = DB::table('financial_reconciliations')->where('tenant_id', $tenantId)->where('id', $id); if ($lock) $q->lockForUpdate(); $row = $q->first(); abort_unless($row, 404, 'Reconciliation not found.'); return $row; }
    private function target(int $tenant, array $data, int $actor): object { if ($data['type'] === 'card') { $method = DB::table('payment_methods')->where('tenant_id', $tenant)->where('id', $data['paymentMethodId'] ?? null)->where('is_active', true)->first(); if (! $method || ! in_array($method->type, ['card', 'wallet'], true) || ! $method->financial_account_id || ! DB::table('financial_accounts')->where('tenant_id', $tenant)->where('id', $method->financial_account_id)->where('is_active', true)->exists()) throw ValidationException::withMessages(['paymentMethodId' => 'Select an active card payment method with an active settlement account.']); $location = $method->financial_location_id ? DB::table('financial_locations')->where('tenant_id', $tenant)->where('id', $method->financial_location_id)->where('is_active', true)->first() : null; if ($method->financial_location_id && ! $location) throw ValidationException::withMessages(['paymentMethodId' => 'The payment method settlement location is not active for this tenant.']); FinancialActor::assertBranchAccess($actor, $tenant, $location?->branch_id ? (int) $location->branch_id : null); return (object) ['financial_account_id' => $method->financial_account_id, 'financial_location_id' => $method->financial_location_id, 'payment_method_id' => $method->id, 'branch_id' => $location?->branch_id]; } $location = DB::table('financial_locations')->where('tenant_id', $tenant)->where('id', $data['financialLocationId'] ?? null)->where('is_active', true)->first(); if (! $location || $location->kind !== $data['type'] || ! DB::table('financial_accounts')->where('tenant_id', $tenant)->where('id', $location->financial_account_id)->where('is_active', true)->exists()) throw ValidationException::withMessages(['financialLocationId' => 'Select an active financial location with an active account matching reconciliation type.']); FinancialActor::assertBranchAccess($actor, $tenant, $location->branch_id ? (int) $location->branch_id : null); return (object) ['financial_account_id' => $location->financial_account_id, 'financial_location_id' => $location->id, 'payment_method_id' => null, 'branch_id' => $location->branch_id]; }
    private function balances(int $tenant, int $account, string $from, string $to): array { $normal = DB::table('financial_accounts')->where('tenant_id', $tenant)->where('id', $account)->value('normal_balance'); $balance = function (?string $date) use ($tenant, $account, $normal): int { $q = DB::table('journal_entry_lines as lines')->join('journal_entries as entries', 'entries.id', '=', 'lines.journal_entry_id')->where('lines.tenant_id', $tenant)->where('lines.financial_account_id', $account)->where('entries.tenant_id', $tenant)->where('entries.status', 'posted'); if ($date) $q->whereDate('entries.entry_date', '<=', $date); $row = $q->selectRaw('COALESCE(SUM(lines.debit), 0) as debit, COALESCE(SUM(lines.credit), 0) as credit')->first(); $d = Money::cents($row->debit); $c = Money::cents($row->credit); return $normal === 'credit' ? $c - $d : $d - $c; }; return [$balance(now()->parse($from)->subDay()->toDateString()), $balance($to)]; }
    private function journalAmount(int $tenant, object $session, object $journal): int { if ($journal->entry_date < $session->date_from || $journal->entry_date > $session->date_to) return 0; $line = $this->journalTotals($tenant, $session, $journal); return max(Money::cents($line->debit), Money::cents($line->credit)); }
    private function journalDirection(int $tenant, object $session, object $journal): ?string { $line = $this->journalTotals($tenant, $session, $journal); $debit = Money::cents($line->debit); $credit = Money::cents($line->credit); if ($debit === $credit) return null; $normal = DB::table('financial_accounts')->where('tenant_id', $tenant)->where('id', $session->financial_account_id)->value('normal_balance'); return (($normal === 'credit') ? $credit > $debit : $debit > $credit) ? 'inflow' : 'outflow'; }
    private function journalTotals(int $tenant, object $session, object $journal): object { return DB::table('journal_entry_lines')->where('tenant_id', $tenant)->where('journal_entry_id', $journal->id)->where('financial_account_id', $session->financial_account_id)->selectRaw('COALESCE(SUM(debit),0) as debit, COALESCE(SUM(credit),0) as credit')->first(); }
    private function remainingLine(int $tenant, object $line): int { return Money::cents($line->amount) - (int) DB::table('financial_reconciliation_matches')->where('tenant_id', $tenant)->where('statement_line_id', $line->id)->sum(DB::raw('matched_amount * 100')); }
    private function remainingJournal(int $tenant, object $session, object $journal): int { return $this->journalAmount($tenant, $session, $journal) - (int) DB::table('financial_reconciliation_matches')->where('tenant_id', $tenant)->where('financial_reconciliation_id', $session->id)->where('journal_entry_id', $journal->id)->sum(DB::raw('matched_amount * 100')); }
    private function line(int $tenant, int $session, int $id, bool $lock): object { $q = DB::table('financial_reconciliation_statement_lines')->where('tenant_id', $tenant)->where('financial_reconciliation_id', $session)->where('id', $id); if ($lock) $q->lockForUpdate(); $row = $q->first(); abort_unless($row, 404, 'Statement line not found.'); return $row; }
    private function editable(object $row, int $tenant, int $actor): void { FinancialActor::assertBranchAccess($actor, $tenant, $row->branch_id ? (int) $row->branch_id : null); if ($row->status === 'completed') throw ValidationException::withMessages(['reconciliation' => 'Completed reconciliations are immutable.']); }
    private function moneyOrNull(mixed $value): ?string { return $value === null ? null : Money::decimal(Money::cents($value)); }
    private function difference(string $type, int $closing, array $data): ?string { $value = $type === 'cash' ? ($data['actualCashCount'] ?? null) : ($data['externalClosingBalance'] ?? null); return $value === null ? null : Money::decimal(Money::cents($value) - $closing); }
    private function storedDifference(object $row, array $data): ?string { return $this->difference($row->type, Money::cents($row->book_closing_balance), ['actualCashCount' => $data['actual_cash_count'], 'externalClosingBalance' => $data['external_closing_balance']]); }
    private function fingerprint(array $data): string { return hash('sha256', json_encode(['type' => $data['type'], 'financialLocationId' => $data['financialLocationId'] ?? null, 'paymentMethodId' => $data['paymentMethodId'] ?? null, 'dateFrom' => $data['dateFrom'], 'dateTo' => $data['dateTo'], 'externalOpeningBalance' => $data['externalOpeningBalance'] ?? null, 'externalClosingBalance' => $data['externalClosingBalance'] ?? null, 'actualCashCount' => $data['actualCashCount'] ?? null, 'notes' => $data['notes'] ?? null], JSON_THROW_ON_ERROR)); }
    private function nextReference(int $tenant): string { return 'REC-'.Str::upper((string) Str::ulid()); }
}
