<?php
namespace Tests\Feature;
use App\Services\FinancialSetupService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;
class DailyClosingApiTest extends TestCase { use RefreshDatabase;
 public function test_daily_closing_requires_actual_cash_then_closes_an_immutable_snapshot():void { $this->seed();$t=$this->tenant();$h=$this->headers($t);$b=(int)DB::table('branches')->where('tenant_id',$t)->where('name','Downtown')->value('id');$preview=$this->getJson("/api/v1/finance/daily-closing?branchId=$b&date=2030-01-01",$h)->assertOk()->json('data');$this->assertFalse($preview['canClose']);$this->assertContains('MISSING_ACTUAL_CASH',array_column($preview['blockers'],'code'));$ready=$this->patchJson("/api/v1/finance/daily-closings/{$preview['id']}",['actualCash'=>'0.00'],$h)->assertOk()->json('data');$this->assertTrue($ready['canClose']);$closed=$this->postJson("/api/v1/finance/daily-closings/{$preview['id']}/close",[],$h)->assertOk()->json('data');$this->assertSame('closed',$closed['status']);$this->patchJson("/api/v1/finance/daily-closings/{$preview['id']}",['actualCash'=>'1.00'],$h)->assertUnprocessable(); }
 public function test_daily_closing_is_tenant_scoped():void{$this->seed();$t=$this->tenant();$h=$this->headers($t);$b=(int)DB::table('branches')->where('tenant_id',$t)->value('id');$id=$this->getJson("/api/v1/finance/daily-closing?branchId=$b&date=2030-01-02",$h)->assertOk()->json('data.id');$f=(int)DB::table('tenants')->insertGetId(['name'=>'Foreign','slug'=>'daily-closing-foreign','status'=>'active','created_at'=>now(),'updated_at'=>now()]);app(FinancialSetupService::class)->ensureForTenant($f);$this->getJson("/api/v1/finance/daily-closings/$id",$this->headers($f))->assertNotFound();}
 private function tenant():int{return (int)DB::table('tenants')->where('slug','cafe-618')->value('id');} private function headers(int $t):array{$u=(int)DB::table('users')->where('tenant_id',$t)->where('role','owner')->value('id');if(!$u)$u=(int)DB::table('users')->insertGetId(['tenant_id'=>$t,'name'=>'Closing Owner','email'=>"closing-$t@test.local",'password'=>bcrypt('x'),'role'=>'owner','is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);$token="closing-$t";DB::table('api_tokens')->updateOrInsert(['tenant_id'=>$t,'user_id'=>$u,'name'=>'closing'],['token_hash'=>hash('sha256',$token),'expires_at'=>now()->addDay(),'created_at'=>now(),'updated_at'=>now()]);return['Authorization'=>"Bearer $token",'X-Tenant-Id'=>$t];}}
