<?php

namespace Tests\Feature;

use Tests\TestCase;

final class FinanceRoutePermissionMapTest extends TestCase
{
    public function test_every_finance_sensitive_route_has_its_canonical_permission(): void
    {
        $expected = [
            'GET api/v1/reports/daily' => 'finance.reports.view', 'GET api/v1/reports/overview' => 'finance.reports.view',
            'GET api/v1/finance/settings/approval-rules' => 'finance.settings.view', 'POST api/v1/finance/settings/approval-rules' => 'finance.settings.manage', 'PATCH api/v1/finance/settings/approval-rules/{rule}' => 'finance.settings.manage',
            'GET api/v1/finance/settings/role-permissions' => 'finance.settings.view', 'GET api/v1/finance/settings/role-permissions/{role}' => 'finance.settings.view', 'PUT api/v1/finance/settings/role-permissions/{role}' => 'finance.settings.manage',
            'GET api/v1/finance/reports' => 'finance.reports.view', 'GET api/v1/finance/reports/profit-loss' => 'finance.reports.view', 'GET api/v1/finance/reports/balance-sheet' => 'finance.reports.view', 'GET api/v1/finance/reports/cash-flow' => 'finance.reports.view', 'GET api/v1/finance/reports/trial-balance' => 'finance.reports.view', 'GET api/v1/finance/reports/general-ledger' => 'finance.reports.view', 'GET api/v1/finance/reports/supplier-aging' => 'finance.reports.view', 'GET api/v1/finance/reports/supplier-statement' => 'finance.reports.view',
            'GET api/v1/finance/accounting-periods' => 'finance.periods.view', 'POST api/v1/finance/accounting-periods' => 'finance.periods.manage', 'GET api/v1/finance/accounting-periods/{period}' => 'finance.periods.view', 'PATCH api/v1/finance/accounting-periods/{period}' => 'finance.periods.manage', 'POST api/v1/finance/accounting-periods/{period}/close' => 'finance.periods.close', 'POST api/v1/finance/accounting-periods/{period}/lock' => 'finance.periods.lock',
            'GET api/v1/finance/setup-status' => 'finance.settings.view', 'GET api/v1/finance/dashboard' => 'finance.view', 'GET api/v1/finance/dashboard/trends' => 'finance.view', 'GET api/v1/finance/dashboard/branches' => 'finance.view',
            'GET api/v1/finance/daily-closing' => 'finance.daily_closing.view', 'GET api/v1/finance/daily-closings' => 'finance.daily_closing.view', 'GET api/v1/finance/daily-closings/{closing}' => 'finance.daily_closing.view', 'PATCH api/v1/finance/daily-closings/{closing}' => 'finance.daily_closing.manage', 'POST api/v1/finance/daily-closings/{closing}/close' => 'finance.daily_closing.close',
            'GET api/v1/finance/accounts' => 'finance.accounts.view', 'POST api/v1/finance/accounts' => 'finance.accounts.manage', 'GET api/v1/finance/accounts/{account}' => 'finance.accounts.view', 'PATCH api/v1/finance/accounts/{account}' => 'finance.accounts.manage', 'PATCH api/v1/finance/accounts/{account}/status' => 'finance.accounts.manage',
            'GET api/v1/finance/journal-entries' => 'finance.journals.view', 'POST api/v1/finance/journal-entries' => 'finance.journals.create', 'GET api/v1/finance/journal-entries/{entry}' => 'finance.journals.view', 'POST api/v1/finance/journal-entries/{entry}/post' => 'finance.journals.post', 'POST api/v1/finance/journal-entries/{entry}/reverse' => 'finance.journals.reverse',
            'GET api/v1/finance/transactions' => 'finance.transactions.view', 'GET api/v1/finance/transactions/branches' => 'finance.transactions.view', 'GET api/v1/finance/transactions/summary' => 'finance.transactions.view', 'GET api/v1/finance/transactions/{transaction}' => 'finance.transactions.view',
            'GET api/v1/finance/reconciliations' => 'finance.reconciliation.view', 'POST api/v1/finance/reconciliations' => 'finance.reconciliation.manage', 'GET api/v1/finance/reconciliations/{reconciliation}' => 'finance.reconciliation.view', 'PATCH api/v1/finance/reconciliations/{reconciliation}' => 'finance.reconciliation.manage', 'GET api/v1/finance/reconciliations/{reconciliation}/system-transactions' => 'finance.reconciliation.view', 'GET api/v1/finance/reconciliations/{reconciliation}/suggestions' => 'finance.reconciliation.view', 'POST api/v1/finance/reconciliations/{reconciliation}/statement-lines' => 'finance.reconciliation.manage', 'PATCH api/v1/finance/reconciliations/{reconciliation}/statement-lines/{line}' => 'finance.reconciliation.manage', 'DELETE api/v1/finance/reconciliations/{reconciliation}/statement-lines/{line}' => 'finance.reconciliation.manage', 'POST api/v1/finance/reconciliations/{reconciliation}/matches' => 'finance.reconciliation.manage', 'DELETE api/v1/finance/reconciliations/{reconciliation}/matches/{match}' => 'finance.reconciliation.manage', 'POST api/v1/finance/reconciliations/{reconciliation}/complete' => 'finance.reconciliation.complete',
            'GET api/v1/finance/cash-accounts' => 'finance.cash_accounts.view', 'POST api/v1/finance/cash-accounts' => 'finance.cash_accounts.manage', 'GET api/v1/finance/cash-accounts/{location}' => 'finance.cash_accounts.view', 'PATCH api/v1/finance/cash-accounts/{location}' => 'finance.cash_accounts.manage', 'PATCH api/v1/finance/cash-accounts/{location}/status' => 'finance.cash_accounts.manage', 'GET api/v1/finance/cash-accounts/{location}/transactions' => 'finance.cash_accounts.view',
            'GET api/v1/finance/bank-accounts' => 'finance.cash_accounts.view', 'POST api/v1/finance/bank-accounts' => 'finance.cash_accounts.manage', 'GET api/v1/finance/bank-accounts/{location}' => 'finance.cash_accounts.view', 'PATCH api/v1/finance/bank-accounts/{location}' => 'finance.cash_accounts.manage', 'PATCH api/v1/finance/bank-accounts/{location}/status' => 'finance.cash_accounts.manage', 'GET api/v1/finance/bank-accounts/{location}/transactions' => 'finance.cash_accounts.view', 'POST api/v1/finance/cash-transfers' => 'finance.cash_transfer.create', 'POST api/v1/finance/cash-transfers/{transfer}/reverse' => 'finance.cash_transfer.reverse',
            'GET api/v1/finance/payment-methods' => 'finance.settings.view', 'POST api/v1/finance/payment-methods' => 'finance.settings.manage', 'PATCH api/v1/finance/payment-methods/{method}' => 'finance.settings.manage', 'PATCH api/v1/finance/payment-methods/{method}/status' => 'finance.settings.manage', 'GET api/v1/finance/expense-categories' => 'finance.settings.view', 'POST api/v1/finance/expense-categories' => 'finance.settings.manage', 'PATCH api/v1/finance/expense-categories/{category}' => 'finance.settings.manage', 'PATCH api/v1/finance/expense-categories/{category}/status' => 'finance.settings.manage',
            'GET api/v1/finance/expenses' => 'finance.expenses.view', 'GET api/v1/finance/expenses/summary' => 'finance.expenses.view', 'GET api/v1/finance/expenses/branches' => 'finance.expenses.view', 'POST api/v1/finance/expenses' => 'finance.expenses.create', 'GET api/v1/finance/expenses/{expense}' => 'finance.expenses.view', 'PATCH api/v1/finance/expenses/{expense}' => 'finance.expenses.edit', 'POST api/v1/finance/expenses/{expense}/submit' => 'finance.expenses.submit', 'POST api/v1/finance/expenses/{expense}/approve' => 'finance.expenses.approve', 'POST api/v1/finance/expenses/{expense}/reject' => 'finance.expenses.reject', 'POST api/v1/finance/expenses/{expense}/pay' => 'finance.expenses.pay', 'POST api/v1/finance/expenses/{expense}/reverse' => 'finance.expenses.reverse',
            'GET api/v1/finance/suppliers' => 'finance.suppliers.view', 'POST api/v1/finance/suppliers' => 'finance.suppliers.manage', 'GET api/v1/finance/suppliers/{supplier}' => 'finance.suppliers.view', 'PATCH api/v1/finance/suppliers/{supplier}' => 'finance.suppliers.manage', 'PATCH api/v1/finance/suppliers/{supplier}/status' => 'finance.suppliers.manage', 'GET api/v1/finance/suppliers/{supplier}/statement' => 'finance.suppliers.view',
            'GET api/v1/finance/supplier-invoices' => 'finance.supplier_invoices.view', 'POST api/v1/finance/supplier-invoices' => 'finance.supplier_invoices.create', 'GET api/v1/finance/supplier-invoices/{invoice}' => 'finance.supplier_invoices.view', 'PATCH api/v1/finance/supplier-invoices/{invoice}' => 'finance.supplier_invoices.edit', 'POST api/v1/finance/supplier-invoices/{invoice}/post' => 'finance.supplier_invoices.post', 'POST api/v1/finance/supplier-invoices/{invoice}/reverse' => 'finance.supplier_invoices.reverse',
            'GET api/v1/finance/supplier-payments' => 'finance.supplier_payments.view', 'POST api/v1/finance/supplier-payments' => 'finance.supplier_payments.create', 'GET api/v1/finance/supplier-payments/{payment}' => 'finance.supplier_payments.view', 'POST api/v1/finance/supplier-payments/{payment}/reverse' => 'finance.supplier_payments.reverse',
        ];
        $routes = collect($this->app['router']->getRoutes())->flatMap(function ($route) { return collect($route->methods())->reject(fn (string $method) => in_array($method, ['HEAD', 'OPTIONS'], true))->mapWithKeys(fn (string $method) => [$method.' '.$route->uri() => $route]); });
        foreach ($expected as $key => $permission) {
            $this->assertTrue($routes->has($key), "Missing registered route: $key");
            $this->assertContains('finance.permission:'.$permission, $routes[$key]->gatherMiddleware(), "Wrong Finance middleware: $key");
        }
        $sensitive = $routes->filter(fn ($route, string $key) => str_contains($key, ' api/v1/finance/') || in_array($key, ['GET api/v1/reports/daily', 'GET api/v1/reports/overview'], true));
        $this->assertSame(count($expected), $sensitive->count(), 'Add every new Finance-sensitive route to this canonical map.');
    }
}
