'use client';

import Link from 'next/link';
import {FormEvent, useMemo, useState} from 'react';
import {useQuery, useQueryClient} from '@tanstack/react-query';
import {api, csrf, queryString} from '@/lib/api/client';
import {Shell} from '@/components/layout/shell';

type Row=Record<string,unknown>;type List={data:Row[]};
const label:Record<string,string>={branches:'الفروع',users:'المستخدمون',plans:'الخطط',subscriptions:'الاشتراكات',analytics:'التحليلات',"audit-logs":'سجل التدقيق',"platform-admins":'مدراء المنصة',announcements:'الإعلانات',system:'صحة النظام',settings:'الإعدادات',profile:'الملف الشخصي'};
const endpoint:Record<string,string>={branches:'/branches',users:'/tenant-users',plans:'/plans',subscriptions:'/subscriptions',"audit-logs":'/audit-logs',"platform-admins":'/platform-admins',announcements:'/announcements',settings:'/settings'};
const columns:Record<string,[string,string][]>={branches:[['name','الفرع'],['tenant_name','المستأجر'],['currency','العملة'],['timezone','المنطقة الزمنية'],['is_active','نشط']],users:[['name','المستخدم'],['email','البريد'],['tenant_name','المستأجر'],['role','الدور'],['is_active','نشط'],['last_login_at','آخر دخول']],plans:[['name','الخطة'],['code','الرمز'],['monthly_price','شهرياً'],['yearly_price','سنوياً'],['currency','العملة'],['feature_count','الميزات'],['is_active','الحالة']],subscriptions:[['tenant_name','المستأجر'],['plan_name','الخطة'],['status','الحالة'],['billing_cycle','الدورة'],['trial_ends_at','نهاية التجربة'],['current_period_ends_at','نهاية الفترة']],"audit-logs":[['action','الإجراء'],['actor_name','الفاعل'],['tenant_name','المستأجر'],['reason','السبب'],['created_at','الوقت']],"platform-admins":[['name','الاسم'],['email','البريد'],['role_name','الدور'],['is_active','نشط'],['last_login_at','آخر دخول']],announcements:[['title','العنوان'],['severity','الأولوية'],['status','الحالة'],['published_at','النشر'],['expires_at','الانتهاء']],settings:[['key','المفتاح'],['value','القيمة'],['updated_at','آخر تحديث']]};
const display=(value:unknown)=>{if(value===null||value===undefined||value==='')return '—';if(typeof value==='boolean'||value===0||value===1)return value?'نعم':'لا';if(typeof value==='object')return JSON.stringify(value);return String(value)};
const badge=(value:unknown)=>{const text=display(value);const tone=/suspend|cancel|critical|past_due|false|0/.test(text)?'danger':/trial|warning|draft/.test(text)?'warning':'success';return <span className={`badge ${tone}`}>{text}</span>};

function ListModule({module}:{module:string}){const [search,setSearch]=useState('');const [status,setStatus]=useState('');const suffix=module==='subscriptions'?queryString({status}):module==='branches'||module==='users'?queryString({search}):module==='audit-logs'?queryString({action:search}):'';const query=useQuery({queryKey:[module,search,status],queryFn:()=>api<List>(`${endpoint[module]}${suffix}`)});const rows=query.data?.data??[];const canEdit=['branches','users','plans','subscriptions','announcements','settings'].includes(module);return <><div className="page-header"><div><h1>{label[module]}</h1><p>{module==='subscriptions'?'متابعة حالة الاشتراكات والتجارب والفترات.':`إدارة ومراجعة ${label[module]}.`}</p></div>{module==='announcements'&&<AnnouncementForm/>}{module==='plans'&&<PlanForm/>}</div>{(module==='branches'||module==='users'||module==='audit-logs'||module==='subscriptions')&&<div className="filters"><input className="input" value={module==='subscriptions'?status:search} onChange={e=>module==='subscriptions'?setStatus(e.target.value):setSearch(e.target.value)} placeholder={module==='subscriptions'?'حالة الاشتراك (active, trialing...)':'بحث أو تصفية'}/></div>}<div className="panel">{query.isLoading?<div className="empty">جارٍ التحميل…</div>:query.isError?<div className="error">تعذّر تحميل هذه الوحدة.</div>:<><div className="table-wrap"><table className="table"><thead><tr>{columns[module].map(([,title])=><th key={title}>{title}</th>)}{canEdit&&<th>إجراء</th>}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id??index)}>{columns[module].map(([field])=><td key={field}>{['status','severity','is_active'].includes(field)?badge(row[field]):display(row[field])}</td>)}{canEdit&&<td><RowAction module={module} row={row}/></td>}</tr>)}</tbody></table></div>{!rows.length&&<div className="empty">لا توجد بيانات ضمن الفلاتر الحالية.</div>}</>}</div></>}

function RowAction({module,row}:{module:string;row:Row}){const client=useQueryClient();const [busy,setBusy]=useState(false);async function update(){const id=Number(row.id);const reason=window.prompt('أدخل سبب التغيير (يحفظ في سجل التدقيق):');if(!reason?.trim())return;let path='';let body:Record<string,unknown>={reason};if(module==='branches'){path=`/branches/${id}`;body.isActive=!Boolean(Number(row.is_active));}else if(module==='users'){path=`/tenant-users/${id}`;body.isActive=!Boolean(Number(row.is_active));body.role=row.role;}else if(module==='subscriptions'){const status=window.prompt('الحالة: trialing أو active أو past_due أو cancelled',String(row.status));if(!status)return;path=`/subscriptions/${id}`;body.status=status;}else if(module==='announcements'){const status=window.prompt('الحالة: draft أو published أو archived',String(row.status));if(!status)return;path=`/announcements/${id}`;body.status=status;}else if(module==='settings'){const value=window.prompt('قيمة JSON الجديدة',display(row.value));if(value===null)return;try{body={value:JSON.parse(value)};}catch{window.alert('يجب إدخال JSON صالح.');return}path=`/settings/${encodeURIComponent(String(row.key))}`;}else if(module==='plans'){path=`/plans/${id}`;body={name:row.name,description:row.description??null,monthlyPrice:Number(row.monthly_price),yearlyPrice:Number(row.yearly_price),currency:row.currency,isActive:!Boolean(Number(row.is_active))};}else return;setBusy(true);try{await csrf();await api(path,{method:'PUT',body:JSON.stringify(body)});client.invalidateQueries({queryKey:[module]});}catch{window.alert('تعذّر حفظ التغيير.')}finally{setBusy(false)}}return <button className="button secondary" disabled={busy} onClick={update}>{busy?'جارٍ الحفظ…':module==='settings'?'تعديل':'تحديث'}</button>}

function PlanForm(){const [open,setOpen]=useState(false);const client=useQueryClient();async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await csrf();await api('/plans',{method:'POST',body:JSON.stringify({code:form.get('code'),name:form.get('name'),description:form.get('description')||null,monthlyPrice:Number(form.get('monthlyPrice')),yearlyPrice:Number(form.get('yearlyPrice')),currency:form.get('currency'),isActive:true})});setOpen(false);client.invalidateQueries({queryKey:['plans']})}return <>{open?<form className="panel form-grid" onSubmit={submit}><label>الاسم<input name="name" required/></label><label>الرمز<input name="code" required/></label><label>شهرياً<input name="monthlyPrice" type="number" min="0" required/></label><label>سنوياً<input name="yearlyPrice" type="number" min="0" required/></label><label>العملة<input name="currency" defaultValue="USD" required/></label><label className="full">الوصف<textarea name="description"/></label><div className="actions full"><button className="button">حفظ الخطة</button><button className="button secondary" type="button" onClick={()=>setOpen(false)}>إلغاء</button></div></form>:<button className="button" onClick={()=>setOpen(true)}>إضافة خطة</button>}</>}

function AnnouncementForm(){const [open,setOpen]=useState(false);const client=useQueryClient();async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await csrf();await api('/announcements',{method:'POST',body:JSON.stringify({title:form.get('title'),message:form.get('message'),severity:form.get('severity'),status:form.get('status'),expiresAt:form.get('expiresAt')||null})});setOpen(false);client.invalidateQueries({queryKey:['announcements']})}return <>{open?<form className="panel form-grid" onSubmit={submit}><label>العنوان<input name="title" required/></label><label>الأولوية<select name="severity"><option value="information">معلومات</option><option value="warning">تنبيه</option><option value="critical">حرج</option></select></label><label>الحالة<select name="status"><option value="draft">مسودة</option><option value="published">منشور</option></select></label><label>تاريخ الانتهاء<input name="expiresAt" type="date"/></label><label className="full">الرسالة<textarea name="message" rows={4} required/></label><div className="actions full"><button className="button">حفظ الإعلان</button><button className="button secondary" type="button" onClick={()=>setOpen(false)}>إلغاء</button></div></form>:<button className="button" onClick={()=>setOpen(true)}>إعلان جديد</button>}</>}

function Analytics(){const query=useQuery({queryKey:['analytics'],queryFn:()=>api<{data:{salesTrend:Row[];tenantGrowth:Row[];subscriptionMix:Row[]}}>('/analytics/overview')});return <><div className="page-header"><div><h1>التحليلات</h1><p>اتجاهات المبيعات والنمو والاشتراكات.</p></div></div>{query.isLoading?<div className="panel empty">جارٍ تحميل التحليلات…</div>:<div className="three-col"><DataPanel title="اتجاه المبيعات" rows={query.data?.data.salesTrend??[]} fields={['date','currency','gross_sales','orders']}/><DataPanel title="نمو المستأجرين" rows={query.data?.data.tenantGrowth??[]} fields={['date','tenants']}/><DataPanel title="مزيج الاشتراكات" rows={query.data?.data.subscriptionMix??[]} fields={['status','total']}/></div>}</>}
function DataPanel({title,rows,fields}:{title:string;rows:Row[];fields:string[]}){return <section className="panel"><h2>{title}</h2><div className="chart-list">{rows.slice(-12).map((row,i)=><div className="status-row" key={i}><span>{fields.map(field=>`${field}: ${display(row[field])}`).join(' · ')}</span></div>)}{!rows.length&&<div className="empty">لا توجد بيانات.</div>}</div></section>}
function Health(){const query=useQuery({queryKey:['health'],queryFn:()=>api<{data:{generatedAt:string;services:{name:string;status:string;value?:unknown}[]}}>('/system/health')});return <><div className="page-header"><div><h1>صحة النظام</h1><p>مراقبة الخدمات الأساسية والطوابير.</p></div></div><div className="panel status-grid">{query.isLoading?<div className="empty">جارٍ الفحص…</div>:query.data?.data.services.map(service=><div className="status-row" key={service.name}><span>{service.name}</span><span>{badge(service.status)} {display(service.value)}</span></div>)}</div></>}
function Profile(){const query=useQuery({queryKey:['profile'],queryFn:()=>api<{data:{name:string;email:string;roles:string[];permissions:string[]}}>('/auth/me')});return <><div className="page-header"><div><h1>الملف الشخصي</h1><p>الصلاحيات والجلسة الحالية.</p></div></div><div className="panel">{query.data&&<><h2>{query.data.data.name}</h2><p>{query.data.data.email}</p><h3>الأدوار</h3><p>{query.data.data.roles.join(', ')}</p><h3>الصلاحيات</h3><p>{query.data.data.permissions.join(', ')||'صلاحيات المدير الأعلى'}</p></>}</div></>}
function TenantDetail({id}:{id:number}){const client=useQueryClient();const [reason,setReason]=useState('');const [status,setStatus]=useState('active');const query=useQuery({queryKey:['tenant',id],queryFn:()=>api<{data:{tenant:Row;branches:Row[];users:Row[];subscription:Row|null;usage:Row}}>(`/tenants/${id}`)});const data=query.data?.data;async function changeStatus(){if(!reason.trim())return;await csrf();await api(`/tenants/${id}/status`,{method:'PUT',body:JSON.stringify({status,reason})});setReason('');client.invalidateQueries({queryKey:['tenant',id]});client.invalidateQueries({queryKey:['tenants']})}return <><div className="page-header"><div><h1>{display(data?.tenant.name??'تفاصيل المستأجر')}</h1><p>{display(data?.tenant.email)}</p></div><Link className="button secondary" href="/tenants">العودة للمستأجرين</Link></div>{query.isLoading?<div className="panel empty">جارٍ التحميل…</div>:query.isError?<div className="panel error">تعذّر تحميل التفاصيل.</div>:data&&<><section className="three-col"><DataPanel title="الفروع" rows={data.branches} fields={['name','currency','is_active']}/><DataPanel title="المستخدمون" rows={data.users} fields={['name','email','role']}/><DataPanel title="الاستخدام" rows={[data.usage]} fields={['orders','products']}/></section><section className="two-col"><div className="panel"><h2>الاشتراك</h2><p>{data.subscription?`${display(data.subscription.plan_name)} · ${display(data.subscription.status)}`:'لا يوجد اشتراك'}</p></div><div className="panel"><h2>تغيير الحالة</h2><div className="filters"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">نشط</option><option value="trial">تجريبي</option><option value="past_due">متأخر</option><option value="suspended">موقوف</option><option value="cancelled">ملغى</option><option value="archived">مؤرشف</option></select><input className="input" value={reason} onChange={e=>setReason(e.target.value)} placeholder="سبب التغيير (مطلوب)"/><button className="button" onClick={changeStatus}>حفظ الحالة</button></div></div></section></>}</>}

export function ModulePage({slug}:{slug:string[]}){const module=slug[0];return <Shell>{module==='tenants'&&slug[1]?<TenantDetail id={Number(slug[1])}/>:module==='analytics'?<Analytics/>:module==='system'&&slug[1]==='health'?<Health/>:module==='profile'?<Profile/>:endpoint[module]?<ListModule module={module}/>:<div className="panel empty">الصفحة غير موجودة.</div>}</Shell>}
